---
core:
  num_workers: 7

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  transform_function: helpers.adapt_host_data
  options:
    host_file: inventory/hosts.yaml
    group_file: inventory/groups.yaml
